EgitimMerkezi/Areas/Admin/Controllers/SliderController.cs
using EgitimMerkezi.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EgitimMerkezi.Areas.Admin.Controllers
{
    public class SliderController : AdminController
    {
        EgitimMerkeziEntities db = new EgitimMerkeziEntities();
        // GET: Admin/Slider
        public ActionResult Index()
        {
            var model = db.Slider.OrderByDescending(x => x.ID).ToList();
            return View(model);
        }

        public ActionResult Add()
        {
            return View();
        }


        const string imageFolderPath = "/Content/slider-images/";
        /// <summary>
        /// Post ile gelen model bu metodda işlenir.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult AddSlider(SliderModel model)
        {
            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                //Dosya kaydetme
                if (model.Resim != null && model.Resim.ContentLength > 0)
                {
                    fileName = model.Resim.FileName;
                    var path = Path.Combine(Server.MapPath("~" + imageFolderPath), fileName);
                    model.Resim.SaveAs(path);
                }

                //EF nesnesi oluşturma
                Slider slider = new Slider();
                slider.BaslangicTarih = model.BaslangicTarih;
                slider.BitisTarih = model.BitisTarih;
                slider.SliderText = model.SliderText;
                slider.ResimYolu = imageFolderPath + fileName;

                db.Slider.Add(slider);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = db.Slider.Find(id);
            //db.Slider.FirstOrDefault(x => x.ID == id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Slider model)
        {
            if (ModelState.IsValid)
            {
                db.Slider.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            else
            {
                return View(model);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = db.Slider.Find(id);
            return View(model);
        }

        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            var model = db.Slider.Find(id);
            db.Slider.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

EgitimMerkezi/Areas/Admin/Views/Slider/Add.cshtml
@model EgitimMerkezi.Areas.Admin.Models.SliderModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div id="page-heading">
    <ol class="breadcrumb">
        <li><a href="index.htm">Dashboard</a></li>
        <li>UI Elements</li>
        <li class="active">Tables</li>
    </ol>

    <h1>Yeni Slider Ekleme</h1>
    <div class="options">
        <div class="btn-toolbar">
            <div class="btn-group hidden-xs">
                <a href='#' class="btn btn-default dropdown-toggle" data-toggle='dropdown'><i class="fa fa-cloud-download"></i><span class="hidden-sm"> Export as  </span><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Text File (*.txt)</a></li>
                    <li><a href="#">Excel File (*.xlsx)</a></li>
                    <li><a href="#">PDF File (*.pdf)</a></li>
                </ul>
            </div>
            <a href="#" class="btn btn-default"><i class="fa fa-cog"></i></a>
        </div>
    </div>
</div>
<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4>Form Layout</h4>

                </div>
                @using (Html.BeginForm("AddSlider", "Slider", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
                {
                    <div class="panel-body">
                        <h3>Basic Form Elements</h3>
                        <p>Try resizing the window to see how the form adapts at smaller screen sizes!</p>
                        <br>

                        <div class="form-group">
                            @Html.LabelFor(m => m.SliderText, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.SliderText, new { @class = "form-control", placeholder = "Slider Yazısı" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.BaslangicTarih, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.BaslangicTarih, new { @class = "form-control datepicker", placeholder = "Başlangıç Tarihi" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.BitisTarih, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.BitisTarih, new { @class = "form-control datepicker", placeholder = "Bitiş Tarihi" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.Resim, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.Resim, new { @class = "form-control", placeholder = "Resim Yolu", type = "file" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>
                        </div>

                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-3">
                                <div class="btn-toolbar">
                                    <button class="btn-primary btn">Submit</button>
                                    <button class="btn-default btn">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section pluginscss
{
    <link rel='stylesheet' type='text/css' href='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.css' />
}

@section jsplugins
{
    <script type='text/javascript' src='~/assets/plugins/codeprettifier/prettify.js'></script>
    <script type='text/javascript' src='~/assets/plugins/easypiechart/jquery.easypiechart.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/sparklines/jquery.sparklines.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/form-toggle/toggle.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.min.js'></script>
}

@section scripts
{
    <script type="text/javascript">
        $('.datepicker').datepicker({
            format: 'mm.dd.yyyy'
        });
    </script>
}

EgitimMerkezi/Areas/Admin/Views/Slider/Delete.cshtml
@model EgitimMerkezi.Slider

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>
Silmek istediğinize emin misiniz?
<br />
@Model.SliderText
<br />
@Html.ActionLink("Kabul Ediyorum", "DeleteConfirm", new { id = Model.ID })
<br />
@Html.ActionLink("Kabul Etmiyorum", "Index")

EgitimMerkezi/Areas/Admin/Views/Slider/Edit.cshtml
@model EgitimMerkezi.Slider

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Slider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.SliderText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SliderText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SliderText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BaslangicTarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BaslangicTarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BaslangicTarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BitisTarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BitisTarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BitisTarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResimYolu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResimYolu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResimYolu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EgitimMerkezi/Areas/Admin/Views/Slider/Index.cshtml
@model List<Slider>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div id="page-heading">
    <ol class="breadcrumb">
        <li><a href="index.htm">Dashboard</a></li>
        <li>UI Elements</li>
        <li class="active">Tables</li>
    </ol>

    <h1>Tables</h1>
    <div class="options">
        <div class="btn-toolbar">
            <div class="btn-group hidden-xs">
                <a href='#' class="btn btn-default dropdown-toggle" data-toggle='dropdown'><i class="fa fa-cloud-download"></i><span class="hidden-sm"> Export as  </span><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Text File (*.txt)</a></li>
                    <li><a href="#">Excel File (*.xlsx)</a></li>
                    <li><a href="#">PDF File (*.pdf)</a></li>
                </ul>
            </div>
            <a href="#" class="btn btn-default"><i class="fa fa-cog"></i></a>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4>Slider Tablosu</h4>
                    <div class="options">

                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Başlangıç Tarihi</th>
                                <th>Bitiş Tarihi</th>
                                <th>Text</th>
                                <th>Resim Yolu</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.BaslangicTarih</td>
                                    <td>@item.BitisTarih</td>
                                    <td>@item.SliderText</td>
                                    <td>@item.ResimYolu</td>
                                    <td>@Html.ActionLink("Düzenle", "Edit", "Slider", new { id = item.ID }, null) | @Html.ActionLink("Sil", "Delete", "Slider", new { id = item.ID }, null) </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>